name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger via GitHub Actions UI
    inputs:
      environment:
        description: 'The environment to destroy (prod, staging, dev)'
        required: true
        default: 'dev'

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

    #  - name: Download Terraform State (if exists)
     #   uses: actions/download-artifact@v3
     #   with:
      #    name: terraform-state
       #   path: MYoffice

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Set Environment Variable
        run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Change to Terraform Directory
        run: |
          cd MYoffice
          ls -l  # Debugging step to check files

      - name: Terraform Init
        run: |
          cd MYoffice
          terraform init

      - name: Terraform Destroy
        run: |
          cd MYoffice
          terraform destroy -auto-approve -input=false -var-file=${{ env.ENV }}/terraform.tfvars
