name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger via GitHub Actions UI
    inputs:
      environment:
        description: 'The environment to destroy (prod, staging, dev)'
        required: true
        default: 'dev'

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Set Environment Variable
        run: echo "ENV=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Change to Terraform Directory
        run: |
          cd MYoffice
          ls -l  # Debugging step to check files
      
      ## Check and Download Terraform State ##
      
      - name: Fetch Artifact Metadata
        id: artifact_metadata
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
            jq -r '.artifacts[] | select(.name=="terraform-state") | .id' || echo "")
          if [[ -n "$ARTIFACT_ID" ]]; then
            echo "FOUND=true" >> $GITHUB_ENV
            echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV
          else
            echo "FOUND=false" >> $GITHUB_ENV
          fi

      - name: Download Terraform State (if exists)
        if: env.FOUND == 'true'
        run: |
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -o terraform-state.zip \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}/zip"
          mkdir -p MYoffice && unzip terraform-state.zip -d MYoffice

      ## Terraform Operations ##
      
      - name: Terraform Init
        run: |
          cd MYoffice
          terraform init

      - name: Terraform Destroy
        run: |
          cd MYoffice
          terraform destroy -auto-approve -input=false -var-file=${{ env.ENV }}/terraform.tfvars
  # Upload again to maintain correct state (althouh empty state file)
      - name: Upload Terraform State
        if: success()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
           name: terraform-state
           path: MYoffice/terraform.tfstate
