name: Terraform Workflow

on:
  push:
    branches:
      - myaws8    # Replace with your branch name
  workflow_dispatch:  # Allow manual runs

jobs:
  terraform:
    name: Terraform Workflow Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # Update to your required version

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      # Step 4: Navigate to the Terraform code directory
      - name: Change to Terraform Directory
        working-directory: .vs/P
        run: echo "Working in $(pwd)"

      # Step 5: Terraform Init
      - name: Terraform Init
        working-directory: .vs/P
        run: terraform init

      # Step 6: Terraform Plan
      - name: Terraform Plan
        working-directory: .vs/P
        run: terraform plan -out=tfplan

      # Step 7: Terraform Apply
      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: .vs/P
        run: terraform apply -auto-approve tfplan
